### ISSUE TITLE
Live reload disabled: Cannot find module '...../chokidar'

### ISSUE THREAD

**Issue by vinaygopinath** [1j01/nw-dev#1]
Hey there,

Thanks for this neat tool for developing nw apps.
I've used it with a different project with success, but I'm having a bit of trouble setting it up with a new one.

Live reload disabled: Error: Cannot find module './node_modules/nw-dev/node_modules/chokidar/'
at dev.js:77

Line 77 in dev.js is

```
      chokidar = window.require("./node_modules/nw-dev/node_modules/chokidar/");
```

It looks like there's an issue with [the commit](https://github.com/1j01/nw-dev/commit/2fdda223766418947801754d7fcaa990975069c1) that started using relative paths

**Comment by vinaygopinath** [comment]
Changing that line to

``` javascript
//Ugly relative path from lib/dev.js
window.require("../node_modules/nw-dev/node_modules/chokidar/");
```

seems to do the trick.

**Comment by 1j01** [comment]
Yeah, ideally the module would be something you'd require, and it would just `require("chokidar")`
I've run into this recently too when I wanted to structure an app differently.
I can probably just have it emulate the `require` resolving algorithm a bit, if need be, so it would look it in both places.

**Comment by 1j01** [comment]
First I tried doing some of this nonsense:

``` coffee
try
    chokidar = window.require "./node_modules/nw-dev/node_modules/chokidar/"
catch e
    dotdots = ".."
    for [0..10]
        console.log "trying", "#{dotdots}/node_modules/nw-dev/node_modules/chokidar/"
        try chokidar ?= window.require "#{dotdots}/node_modules/nw-dev/node_modules/chokidar/"
        dotdots = "../#{dotdots}"
    console.warn "Live reload disabled:", e.stack
```

But then I realized I could just do

``` coffee
try
    chokidar = window.require "nw-dev/node_modules/chokidar/"
catch e
    console.warn "Live reload disabled:", e.stack
```

**Comment by 1j01** [comment]
Published `nw-dev@1.2.1`

**Comment by vinaygopinath** [comment]
Thanks @1j01

**Comment by 1j01** [comment]
No problem :smiley:
