### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by 1j01** [1j01/nw-dev#6]
Probably like the other icons on the [nw.js website](https://nwjs.io/) for individual features, such as:

![](https://nwjs.io/img/icon_puzzle.png)

But with a reload icon.

![nwjs like icon quick jspaint mockup](https://user-images.githubusercontent.com/3630663/30224702-c61bdbd6-949d-11e7-8e1b-0272c8d6d475.png)

> The mockup's shitty
> Non-legitty
> But, I think it
> Could be pretty

Maybe more like a compass, with the circular arrow also implying motion on the compass...

![nwjs like icon quickly done in jspaint 1](https://user-images.githubusercontent.com/3630663/30246221-6fa7dc44-95c1-11e7-8322-fe59b4816e8f.png) ![nwjs like icon quickly done in jspaint 2](https://user-images.githubusercontent.com/3630663/30246247-8f7d7302-95c2-11e7-94d2-7f8b53146e7f.png) ![nwjs like icon quickly done in jspaint 3](https://user-images.githubusercontent.com/3630663/30246242-71dbd758-95c2-11e7-9198-125db85ae60d.png) ![nwjs like icon quickly done in jspaint 5](https://user-images.githubusercontent.com/3630663/30246244-80841220-95c2-11e7-9729-7253cf4a41aa.png)

Eh, that feels unnecessarily complicated. And those all look really ugly.

> Plus unnecessarily
> Forming a G
> At least the last two icons
> For me that's what I see

> If it formed a D
> It would make more sense
> But even that would be
> Unnecessary

**Comment by ayushmanchhabra** [comment]
> ![nwjs like icon quick jspaint mockup](https://user-images.githubusercontent.com/3630663/30224702-c61bdbd6-949d-11e7-8e1b-0272c8d6d475.png)

@1j01 this one seems like a good candidate - i like it since it accurately represents the state of the nw ecosystem 😆
