### ISSUE TITLE
Request to move repo under NW Userland

### ISSUE THREAD

**Issue by ayushmanchhabra** [1j01/nw-dev#7]
Hi @1j01,

I'm part of a GitHub org called [NW Utils](https://github.com/nwutils). I'm trying to consolidate NW tooling so it's easier to find useful projects and give much needed life to stagnant ones. I also think this would be a great opportunity to exchange ideas and learn new things. Let me know what you think and if you’d be willing to.

Best Regards
Ayushman

**Comment by 1j01** [comment]
Hey, I just saw this.
It sounds like a good idea. I'd be happy to move my repo over if you're still interested.

**Comment by ayushmanchhabra** [comment]
Awesome you can contact Jared on the NW.js chatroom since he has admin access.
https://gitter.im/nwjs/nw.js

**Comment by TheJaredWilcurt** [comment]
@1j01 I invited you as a member of nwutils, if you want to move the repo over I'll add you as an admin of it, so nothing really changes, your repo is just easier to find by the commnunity.

**Comment by 1j01** [comment]
Transferred it.

**Comment by TheJaredWilcurt** [comment]
Set you as admin. Should be good :+1:
